### ISSUE TITLE
Multiwfn with fpm

### ISSUE THREAD

**Issue by aslozada** [digital-chemistry-laboratory/multiwfn-mac-build#2]
Nice!
What do you think about building the program with fpm < https://fpm.fortran-lang.org/en/index.html >?

**Comment by kjelljorner** [comment]
It's a good idea. I tried it very quickly but couldn't get it to work with the default folder structure of Multiwfn.

```toml
name = "multiwfn-mac-build"
version = "0.0.1"
license = "MIT"
author = "Kjell Jorner"
maintainer = "kjell.jorner@gmail.com"
copyright = "Copyright 2022, Kjell Jorner"

[library]
source-dir = "."

[[ executable ]]
name = "multiwfn"
source-dir = "."
main = "Multiwfn.f90"

[install]
library = false
```

I get the following error. Also, the compiler flags to handle the non-standard code and the Fortran preprocessing would need to be added. Maybe you can take a look if you have time and interest.

```
(base) kjelljorner@mba-m1-kjell-jorner Multiwfn % fpm run
<ERROR>*cmd_run*:targets error:Unable to find source for module dependency: "util" used by "././libreta_hybrid/libreta.f90"
STOP 1
```
